### ISSUE TITLE
Sidebar Responsive Issue

### ISSUE THREAD

**Issue by ozziexsh** [Beat-Nick/erb2slim#11]
Hey! Came from the reddit thread. When full-width on my macbook air (13") using [Brave](https://github.com/brave/browser-laptop) browser, I see this:

![screen shot 2017-05-30 at 8 36 29 am](https://cloud.githubusercontent.com/assets/2093630/26588716/553a408a-4513-11e7-9281-8d2b0d66d5d5.png)

Note I have scroll bars turned to always on.

**Comment by ghost** [comment]
Seconded, I'm on Chrome on Ubuntu seeing the same. Need to zoom out to 67% to see the convert button

**Comment by Beat-Nick** [comment]
@nehero @MaxPleaner 
I finally got around to fixing this. I've set min-height & min-width which should hopefully resolve your issue. Please let me know if it's still a problem, and if so, your screen resolution. You will most likely have to clear cache to pull the new css files (ctrl-f5 in chrome).

32c4955bf420f56ef32d5c4b640c0e9be0932dcf
