### ISSUE TITLE
Wrong display on Firefox Quantum relase

### ISSUE THREAD

**Issue by dceluis** [Beat-Nick/erb2slim#13]
Hi, I was trying to use the tool and got this screen displayed:

![image](https://user-images.githubusercontent.com/5464881/34176523-2ab69cb8-e4ce-11e7-9f18-6eeb91262aa1.png)

The convert button is unclickable. And I got no console errors.
Notice the page overflowing the window size.

![image](https://user-images.githubusercontent.com/5464881/34176552-47768552-e4ce-11e7-82ae-852573ba859b.png)

Hope it helps!

**Comment by dceluis** [comment]
Btw, it seems it's an issue with the conversion counter div. Removing the element restored the functionality:
![image](https://user-images.githubusercontent.com/5464881/34176683-dd4b0d46-e4ce-11e7-970c-fc0f3d9a8ebc.png)

**Comment by Beat-Nick** [comment]
Thanks for in the in-depth response. I'll take a look how the counter flows in the css.

**Comment by thebradhimself** [comment]
Just noticed this myself.  Came to report an issue

**Comment by Beat-Nick** [comment]
This issue stems from outdated dependencies in flipclock.js, which hasn't been updated in a few years. I've tried a few forks of the project with no success. A quick look at analytics shows about 6% of the user base uses firefox, not sure how many use the most recent version. I will leave the issue open for now but I'm not willing to go in and dig through flipclock.js to preformed the required updates.
