### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by dedman** [Beat-Nick/erb2slim#14]
Hey there! 

Firstly thank you for your website, it is a incredible resource when taking the gradual approach to migrate a project with ERB over to SLIM. 

If you have time to check it out, http://erb2slim.com/  is currently down. 

Thank you for your work.

**Comment by Beat-Nick** [comment]
After the Intel cpu issues MS update vms and it broke mine hard it seems, unable even to SSH in. I've opened a ticket and hope to have the server live by the end of the weekend. Thanks for the heads up.

**Comment by Beat-Nick** [comment]
The whole disk died and it took me a few days to put everything back together. It's back up and running now.
