### ISSUE TITLE
ErbToSlim problem with '\'

### ISSUE THREAD

**Issue by ExplosiveGM** [Beat-Nick/erb2slim#17]
When try convert erb to slim for example
`    <legend>  
      <%= link_to(  
        field.display_associated_resource,  
        [namespace, field.data],  
      ) %>
    </legend>  `
It create 
`legend  
  = link_to(                             \  
      field.display_associated_resource, \  
      [namespace, field.data],           \  
    )                                    \  `
Where last symbol '\\' make error for slim parser

**Comment by Beat-Nick** [comment]
I'm not sure where the back slashes are coming in.... my translation goes from:

```
<legend> <%= link_to( field.display_associated_resource, [namespace, field.data], ) %> </legend> 
```
which spits out as

```
legend
  = link_to( field.display_associated_resource, [namespace, field.data], )
```

Which is formatted correctly. Please look into the white space or perhaps the extra comma on the end of the link_to()
