### ISSUE TITLE
Attribute values in Erb2Slim

### ISSUE THREAD

**Issue by sdeframond** [Beat-Nick/erb2slim#2]
Hi there! Thanks a lot for the awesome work.

Here is a strange case where I believe we don't get the result we would expect. Using http://erb2slim.com/,

``` erb
 <div class="form-group" ng-init="foobar = '<%= @foobar %>'"></div>
```

becomes

``` slim
|  <div class="form-group" ng-init="foobar = '
= @foobar
| '">
```

Is it normal?

**Comment by Beat-Nick** [comment]
This is mostly due to the fact that the HTML2SLIM gem not being as fully developed as the HTML2HAML. By default I suggest using HAML -> SLIM as the conversion tends to go a bit smoother. With that you get the following:

`.form-group ng-init=("foobar = '#{@foobar}'")`
