### ISSUE TITLE
https

### ISSUE THREAD

**Issue by equivalent** [Beat-Nick/erb2slim#20]
on website http://erb2slim.com/ 

would you consider `https` ? 

reason: sometimes developers may want to paste ERB template that contains bit of "private" logic and this may be security issue if you are in e.g. coffee place 

there is a easy way how to get HTTPS for free when using services like CloudFlare DNS  https://www.cloudflare.com/ ) (I don't work for them I just use them)   for example my websites like https://blog.eq8.eu/  https://bjjnitra.sk/ https://elkar.sk/  are set up this way 

I can help you set this up if you want

**Comment by Beat-Nick** [comment]
Yep, it's a good point. I took this a good excuse to update some dependencies and do a bit of clean up. The app should show as secure now but DNS could take up to 48 hours to process.

**Comment by equivalent** [comment]
![Screenshot from 2020-08-26 10-23-00](https://user-images.githubusercontent.com/721990/91279727-288a2f00-e786-11ea-87fb-e2d0e41f7004.png)

works :clap: 

![](https://meme.eq8.eu/cookie.jpg)
