### ISSUE TITLE
Counter displaying issues

### ISSUE THREAD

**Issue by dam13n** [Beat-Nick/erb2slim#21]
Conversion counter is overlapping on the Convert button and is also overflowing to next line:
![image](https://user-images.githubusercontent.com/6476222/92521146-96e0df80-f1d1-11ea-8b8f-01743da1660b.png)

**Comment by salty-catpuccino** [comment]
Same issue here, wanted to point out that this happens on smaller screens as I dont run into this on my larger screens.
