### ISSUE TITLE
Preserve whitespace

### ISSUE THREAD

**Issue by georgejas** [Beat-Nick/erb2slim#4]
When I enter this paragraph:
`<p>Or click <a href="adsf">asdf</a> Convert to test it out!</p>` 

It gets converted to:

```
p
  | Or click
  a href="adsf"  asdf
  | Convert to test it out!
```

But it should be converted to:

```
p
  ' Or click
  a href="adsf"  asdf
  | Convert to test it out!
```

(Note the single quote ' to preserve the whitespace at the end of the first line, so that "click" and "asdf" aren't joined together.)

**Comment by Beat-Nick** [comment]
You are correct but my project was to only build a pretty front-end for the plugins, I don't actually do any development on the translations. I've just double checked that I have the latest versions of each so please feel free to open an issue on the appropriate github page linked on the bottom of the website or in this repo's readme.
