### ISSUE TITLE
dark style hide select and select all text | ctrl+a

### ISSUE THREAD

**Issue by mibamur** [Beat-Nick/erb2slim#5]
Hi @Beat-Nick 
css need corect

**Comment by Beat-Nick** [comment]
Hello @mibamur, I'm not sure what you mean. Are you suggesting that the code highlighting needs to be a lighter color, or is there some area where ctrl+a is working incorrectly?

**Comment by mibamur** [comment]
ctrl+a work correct
highlighting should be lighter
sorry

**Comment by Beat-Nick** [comment]
Old issue but I finally got around to lightening the highlight, just wanted to reference here:

4d5f72e5a45d70ceecf7fce570bcdb389ae47c44
