### ISSUE TITLE
Extra \ in link tags

### ISSUE THREAD

**Issue by lomefin** [Beat-Nick/erb2slim#6]
When converting 

```
<%= link_to 'Cerrar sesión', destroy_user_session_url, method: :delete,
                      data: { target: '#' }, class: "btn btn-danger-outline btn-block" %>
```

Converts to 

```
= link_to 'Cerrar sesión', destroy_user_session_url, method: :delete, \
  data: { target: '#' }, class: "btn btn-danger-outline btn-block"    \
```

So it thinks the next line also goes in the link, in my case it has an 
`- else` tag so my template broke.

**Comment by Beat-Nick** [comment]
Thanks for using the site. Please check out [Issue #8](https://github.com/Beat-Nick/erb2slim/issues/8) for the answer to this.
