### ISSUE TITLE
"#{}" conversions with missing "{}"

### ISSUE THREAD

**Issue by ghost** [Beat-Nick/erb2slim#7]
Hello,

Since a few days I noticed that in some conversions there were important missing characters, as:
`<%= "#{lorem.ipsum} - Lorem ipsum" %>` which does `= "# lorem.ipsum - Lorem ipsum"`

Can't find the precise example, but I'll put it here when I'll find it. Thank you in advance for helping.

**Comment by Beat-Nick** [comment]
Thanks for using the site. Please check out [Issue #8](https://github.com/Beat-Nick/erb2slim/issues/8) for the answer to this.
