### ISSUE TITLE
When try to convert ERB 2 SLIM content with non US-ASCII symbols

### ISSUE THREAD

**Issue by AM-R** [Beat-Nick/erb2slim#9]
I see the error when I try to convert content from ERB or HTML to SLIM directly without some US-ASCII. It's working before correctly but now report an error!

`"invalid byte sequence in US-ASCII"`

Maybe just keep the uncorrect symbols on their places without erorr or with highlighting?

Thanks.

![1477282595354](https://cloud.githubusercontent.com/assets/13679833/19633451/8d952858-99e4-11e6-83cf-1a820a35330e.png)

**Comment by Beat-Nick** [comment]
Issue been fixed with the following commit and is now live. Please let me know if you have any other issues.

5ba18b01db1a97afa0b17b2258272745d7b473a1
